{
 "title": "GitHub",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "repo",
    "label": "Repositories",
    "query": {
     "query": "label_values(github_exporter_repo_stargazers, repo)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pull Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Open Pull Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (repo) (github_exporter_pr_info{repo=~\"$repo\",state=\"open\"})",
     "legendFormat": "{{ repo }}"
    }
   ]
  },
  {
   "title": "Open Pull Requests By Team",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (team) (github_exporter_pr_info{repo=~\"$repo\",state=\"open\",team!=\"\"})",
     "legendFormat": "{{ team }}"
    },
    {
     "expr": "sum by (team) (github_exporter_pr_info{repo=~\"$repo\",state=\"open\",team=\"\"})",
     "legendFormat": "(no team)"
    }
   ]
  },
  {
   "title": "Open Pull Requests By Author",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (author) (github_exporter_pr_info{repo=~\"$repo\",state=\"open\"})",
     "legendFormat": "{{ author }}"
    }
   ]
  },
  {
   "title": "Open Pull Request Latency",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 11 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (latency) (github_exporter_pr_info{repo=~\"$repo\",state=\"open\"})",
     "legendFormat": "{{ latency }}"
    }
   ]
  },
  {
   "title": "Latency from PR creation -> close/merge",
   "type": "piechart",
   "description": "The time from PR creation to either close/merge. Add regexes to the PR number to see the most recent data e.g number=~\"2\\\\d\\\\d\\\\d\" for all PR 2xxx",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (latency) (github_exporter_pr_info{repo=~\"$repo\",state!=\"open\",number=~\"2\\\\d\\\\d\\\\d\"})",
     "legendFormat": "{{ latency }}"
    }
   ]
  },
  {
   "title": "Open Pull Requests By Review State",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 11 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (review) (github_exporter_pr_info{repo=~\"$repo\",state=\"open\"})",
     "legendFormat": "{{ review }}"
    }
   ]
  },
  {
   "title": "Issues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Open P1, P2 Issues",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (repo) (github_exporter_issue_info{repo=~\"$repo\",state=\"open\",priority=\"P?\"})",
       "legendFormat": "{{ repo }} P?"
      },
      {
       "expr": "sum by (repo) (github_exporter_issue_info{repo=~\"$repo\",state=\"open\",priority=\"P1\"})",
       "legendFormat": "{{ repo }} P1"
      },
      {
       "expr": "sum by (repo) (github_exporter_issue_info{repo=~\"$repo\",state=\"open\",priority=\"P2\"})",
       "legendFormat": "{{ repo }} P2"
      }
     ]
    },
    {
     "title": "Open Issues by Type (T)",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 22 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum by (T) (github_exporter_issue_info{repo=~\"$repo\",state=\"open\",T!=\"\"})",
       "legendFormat": "{{ T }}"
      },
      {
       "expr": "sum by (T) (github_exporter_issue_info{repo=~\"$repo\",state=\"open\",T=\"\"})",
       "legendFormat": "(no T)"
      }
     ]
    },
    {
     "title": "Open Issues by Priority (P)",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 22 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum by (priority) (github_exporter_issue_info{repo=~\"$repo\",state=\"open\",priority!=\"\"})",
       "legendFormat": "{{ priority }}"
      },
      {
       "expr": "sum by (priority) (github_exporter_issue_info{repo=~\"$repo\",state=\"open\",priority=\"\"})",
       "legendFormat": "(no priority)"
      }
     ]
    },
    {
     "title": "Open Issues by Team",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 32 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum by (team) (github_exporter_issue_info{repo=~\"$repo\",state=\"open\",team!=\"\"})",
       "legendFormat": "{{ team }}"
      },
      {
       "expr": "sum(github_exporter_issue_info{repo=~\"$repo\",state=\"open\",team=\"\"})",
       "legendFormat": "(no team)"
      }
     ]
    },
    {
     "title": "Open Issues by Author",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 32 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum by (author) (github_exporter_issue_info{repo=~\"$repo\",state=\"open\"})",
       "legendFormat": "{{ author }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Milestones",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Open Milestone Completion",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "github_exporter_milestone_info * on (repo, number) group_right(title) (:github_exporter_repo_open_milestone_completion:{repo=~\"$repo\"})",
       "legendFormat": "{{ repo }} / {{ title }}"
      }
     ]
    },
    {
     "title": "Open Milestone Completion",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "github_exporter_milestone_info * on (repo, number) group_right(title) (:github_exporter_repo_open_milestone_completion:{repo=~\"$repo\"})",
       "legendFormat": "{{ repo }} / {{ title }}"
      }
     ]
    }
   ]
  },
  {
   "title": "General Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Stargazers",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (repo) (github_exporter_repo_stargazers{repo=~\"$repo\"})",
     "legendFormat": "{{ repo }}"
    }
   ]
  },
  {
   "title": "Forks",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (repo) (github_exporter_repo_forks{repo=~\"$repo\"})",
     "legendFormat": "{{ repo }}"
    }
   ]
  },
  {
   "title": "Watchers",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (repo) (github_exporter_repo_watchers{repo=~\"$repo\"})",
     "legendFormat": "{{ repo }}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (repo) (github_exporter_repo_disk_usage_bytes{repo=~\"$repo\"})",
     "legendFormat": "{{ repo }}"
    }
   ]
  },
  {
   "title": "Languages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$repo",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 45 },
     "repeat": "repo",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "github_exporter_repo_language_size_bytes{repo=\"$repo\"}",
       "legendFormat": "{{ language }}"
      }
     ]
    }
   ]
  },
  {
   "title": "API Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "API Request Rate",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (repo) (rate(github_exporter_api_requests_total{repo=~\"$repo\"}[60m]))",
       "legendFormat": "{{ repo }}"
      }
     ]
    },
    {
     "title": "API Points Remaining",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "github_exporter_api_points_remaining",
       "legendFormat": "points"
      }
     ]
    }
   ]
  }
 ]
}